### ISSUE TITLE
Fix badges

### ISSUE THREAD

**Issue by antongulenko** [bitflow-stream/bitflow4j#14]
The badges (Travis CI, code climate, etc) are based on the bitflow4j develop branch. They must be changed to reflect the master branch. I think, only Coveralls must be configured to use the master branch by default, but it seems to require a login, so I cannot change it.

**Comment by JohannesOhlemacher** [comment]
Coveralls.io is now set to master. To be more specific it is set to the default repo branch. If the branch is changed one has to got to coveralls.io -> bitflow4j -> settings -> resync with github.
